Wrap Billing client crash with ours with more information (#2296)
### Description
Billing client 7.1.x introduced a crash in some older android devices
due to it not finding a class:
```
FATAL EXCEPTION: main
Process: com.revenuecat.purchases_sample, PID: 20072
java.lang.NoClassDefFoundError: com.android.billingclient.api.zzce
	at com.android.billingclient.api.BillingFlowParams$Builder.build(com.android.billingclient:billing@@7.1.1:3)
```
This gets fixed downgrading to Billing client 7.0.0 or enabling core
library desugaring (preferred option):
https://developer.android.com/studio/write/java8-support#groovy

Since this crash is difficult to understand, we are wrapping the
relevant errors with our own. This is how it looks like now:
```
FATAL EXCEPTION: main
Process: com.revenuecat.purchases_sample, PID: 344
com.revenuecat.purchases. NoCoreLibraryDesugaringException: Error building BillingFlowParams for subscriptions due to an issue in Google's Billing Client library. Please check TODO-LINK to fix this issue.
	at com.revenuecat.purchases.google.BillingWrapper.buildSubscriptionPurchaseParams(BillingWrapper.kt:959)
	at com.revenuecat.purchases.google.BillingWrapper.buildPurchaseParams(BillingWrapper.kt:893)
	at com.revenuecat.purchases.google.BillingWrapper.access$buildPurchaseParams(BillingWrapper.kt:80)
	at com.revenuecat.purchases.google.BillingWrapper$makePurchaseAsync$2.invoke(BillingWrapper.kt:296)
	at com.revenuecat.purchases.google.BillingWrapper$makePurchaseAsync$2.invoke(BillingWrapper.kt:295)
	at com.revenuecat.purchases.google.BillingWrapper.executePendingRequests$lambda$3$lambda$2$lambda$1(BillingWrapper.kt:144)
	at com.revenuecat.purchases.google.BillingWrapper.$r8$lambda$g3n3vaI7ScqYgOQ9PPJyLRTbbfM(BillingWrapper.kt)
	at com.revenuecat.purchases.google.BillingWrapper$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NoClassDefFoundError: com.android.billingclient.api.zzce
	at com.android.billingclient.api.BillingFlowParams$Builder.build(com.android.billingclient:billing@@7.1.1:3)
	at com.revenuecat.purchases.google.BillingWrapper.buildSubscriptionPurchaseParams(BillingWrapper.kt:955)
```