Fix potential `NoClassDefFoundError` crash finding `Icons` caused by material3 1.4.0  (#2727)
It looks like material3 1.4.0 pulled the dependency from
material-icons-core (release notes
[here](https://developer.android.com/jetpack/androidx/releases/compose-material3#compose_material3_version_14_2)).
We do depend transitively on version 1.3.0, which has the dependency,
but if your app is overriding that to 1.4.0, the app will crash with:

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/icons/Icons;
       at com.revenuecat.purchases.ui.revenuecatui.customercenter.InternalCustomerCenterKt$CustomerCenterNavigationIcon$2.invoke(InternalCustomerCenter.kt:355)
```