Fixes more Icons crashing with `NoClassDefFoundError` when using Material 1.4.0 (#2732)
#2727 fixed some Icons, but I somehow missed some other `Icons` being
used in other parts of the code. This PR adds the missing ones:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/material/icons/Icons$Rounded;
```

(cherry picked from commit b82598ee51561aa32f158b151a2124553a677f61)