Set default interfaces compiler flag to `all-compatibility` (#2227)
Without this, the binary is not compatible since with just `all` it
doesn't generate `DefaultImpls` classes are generated.

I noticed this because when doing a mismatching version in react native
between purchases-android and phc I was getting runtime issues:

```
  implementation 'com.revenuecat.purchases:purchases:8.14.0'
  implementation 'com.revenuecat.purchases:purchases-ui:8.14.0'
  implementation 'com.revenuecat.purchases:purchases-hybrid-common-ui:13.22.0'
```  

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/revenuecat/purchases/models/StoreProduct$DefaultImpls;
at com.revenuecat.purchases.hybridcommon.mappers.StoreProductMapperKt.map(StoreProductMapper.kt:49)
...
```

More info about this
[here](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/#new-modes-for-generating-default-methods-in-interfaces)